CREATE DATABASE PETSHOP;
USE PETSHOP;

CREATE TABLE `MODULO_USUARIO` (
  `ID_MODULO_USUARIO` int NOT NULL,
  `TITULO` varchar(50) DEFAULT NULL,
  `DESCRIPCION` char(100) DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL COMMENT 'A:ACTIVO, I:INACTIVO',
  PRIMARY KEY (`ID_MODULO_USUARIO`)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `GRUPO_USUARIO` (
  `ID_GRUPO_USUARIO` int NOT NULL,
  `NOMBRE_GRUPO` varchar(100) DEFAULT NULL,
  `DESCRIPCION` varchar(100) DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL COMMENT 'A:ACTIVO, I:INACTIVO, X:ANULADO',
  PRIMARY KEY (`ID_GRUPO_USUARIO`)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `PERMISO_USUARIO` (
  `ID_PERMISO_USUARIO` int NOT NULL,
  `ID_GRUPO_USUARIO`  int NOT NULL COMMENT 'ROL USUARIO',
  `ID_MODULO_USUARIO` int NOT NULL,
  `R` int DEFAULT NULL,
  `W` int DEFAULT NULL,
  `U` int DEFAULT NULL,
  `D` int DEFAULT NULL,
  PRIMARY KEY (`ID_PERMISO_USUARIO`),
  FOREIGN KEY (`ID_GRUPO_USUARIO`) REFERENCES `GRUPO_USUARIO`(ID_GRUPO_USUARIO),
  FOREIGN KEY (`ID_MODULO_USUARIO`) REFERENCES `MODULO_USUARIO`(ID_MODULO_USUARIO)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `USUARIO` (
  `ID_USUARIO` int NOT NULL,
  `NOMBRE` varchar(100) DEFAULT NULL,
  `APELLIDO` varchar(100) DEFAULT NULL,
  `CORREO` varchar(80) NOT NULL,
  `CONTRASENIA` varchar(100) DEFAULT NULL,
  `ID_GRUPO_USUARIO` int DEFAULT NULL,
  `USUARIO_REG` varchar(80) DEFAULT NULL,
  `FECHA_REG` datetime DEFAULT NULL,
  `USUARIO_MOD` varchar(80) DEFAULT NULL,
  `FECHA_MOD` datetime DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL COMMENT 'A:ACTIVO, I:INACTIVO, X:ANULADO',
  `TOKEN` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`, `CORREO`),
  FOREIGN KEY (`ID_GRUPO_USUARIO`) REFERENCES `GRUPO_USUARIO`(ID_GRUPO_USUARIO)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `PROVEEDOR` (
  `ID_PROVEEDOR` int NOT NULL,
  `RUC` char(11) DEFAULT NULL,
  `NOMBRE` varchar(100) DEFAULT NULL,
  `DIRECCION` varchar(100) DEFAULT NULL,
  `TELEFONO` varchar(20) DEFAULT NULL,
  `USUARIO_REG` varchar(80) DEFAULT NULL,
  `FECHA_REG` datetime DEFAULT NULL,
  `USUARIO_MOD` varchar(80) DEFAULT NULL,
  `FECHA_MOD` datetime DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL COMMENT 'A:ACTIVO, I:INACTIVO, X:ANULADO',
  PRIMARY KEY (`ID_PROVEEDOR`)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `CATEGORIA` (
  `ID_CATEGORIA` int NOT NULL,
  `NOMBRE` varchar(100) DEFAULT NULL,
  `USUARIO_REG` varchar(80) DEFAULT NULL,
  `FECHA_REG` datetime DEFAULT NULL,
  `USUARIO_MOD` varchar(80) DEFAULT NULL,
  `FECHA_MOD` datetime DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL COMMENT 'A:ACTIVO, I:INACTIVO, X:ANULADO',
  PRIMARY KEY (`ID_CATEGORIA`)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `ARCHIVO` (
  `ID_ARCHIVO` int NOT NULL,
  `NOMBRE` varchar(100) DEFAULT NULL,
  `EXTENSION` varchar(10) DEFAULT NULL,
  `RUTA` varchar(100) DEFAULT NULL,
  `RAIZ` varchar(100) DEFAULT NULL,
  `USUARIO_REG` varchar(80) DEFAULT NULL,
  `FECHA_REG` datetime DEFAULT NULL,
  `USUARIO_MOD` varchar(80) DEFAULT NULL,
  `FECHA_MOD` datetime DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL COMMENT 'A:ACTIVO, X:ANULADO',
  PRIMARY KEY (`ID_ARCHIVO`)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `PRODUCTO` (
  `ID_PRODUCTO` int NOT NULL,
  `ID_PROVEEDOR` int DEFAULT NULL,
  `ID_CATEGORIA` int DEFAULT NULL,
  `NOMBRE` varchar(100) DEFAULT NULL,
  `STOCK` int DEFAULT NULL,
  `PRECIO` decimal(11,2) DEFAULT NULL,
  `PESO` int DEFAULT NULL,
  `FECHA_VENCIMIENTO` datetime DEFAULT NULL,
  `MASCOTA` varchar(10) DEFAULT NULL COMMENT 'PERRO, GATO',
  `TAMANIO_MASCOTA` varchar(10) DEFAULT NULL COMMENT 'PEQUENIO, MEDIANO, GRANDE',
  `CICLO_VIDA_MASCOTA` varchar(10) DEFAULT NULL COMMENT 'CACHORRO, ADOLESCENTE, ADULTO, SENIOR',
  `USUARIO_REG` varchar(80) DEFAULT NULL,
  `FECHA_REG` datetime DEFAULT NULL,
  `USUARIO_MOD` varchar(80) DEFAULT NULL,
  `FECHA_MOD` datetime DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL COMMENT 'A:ACTIVO, I:INACTIVO, X:ANULADO, D:DESPERFECTO',
  PRIMARY KEY (`ID_PRODUCTO`),
  FOREIGN KEY (`ID_PROVEEDOR`) REFERENCES `PROVEEDOR`(ID_PROVEEDOR),
  FOREIGN KEY (`ID_CATEGORIA`) REFERENCES `CATEGORIA`(ID_CATEGORIA)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `PRODUCTO_ARCHIVO` (
  `ID_PRODUCTO_ARCHIVO` int NOT NULL,
  `ID_PRODUCTO` int NOT NULL,
  `ID_ARCHIVO` int NOT NULL,
  `USUARIO_REG` varchar(80) DEFAULT NULL,
  `FECHA_REG` datetime DEFAULT NULL,
  `USUARIO_MOD` varchar(80) DEFAULT NULL,
  `FECHA_MOD` datetime DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL COMMENT 'A:ACTIVO, X:ANULADO',
  PRIMARY KEY (`ID_PRODUCTO_ARCHIVO`),
  FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO`(ID_PRODUCTO),
  FOREIGN KEY (`ID_ARCHIVO`) REFERENCES `ARCHIVO`(ID_ARCHIVO)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `PROMOCION` (
  `ID_PROMOCION` int NOT NULL,
  `ID_PRODUCTO` int NOT NULL,
  `TIPO_PROMOCION` CHAR(1) NOT NULL COMMENT 'O:OFERTA, P:PROMOCION, L:LIQUIDACION',
  `DESCRIPCION` varchar(100) DEFAULT NULL,
  `CANTIDAD` int DEFAULT NULL COMMENT 'CANTIDAD PARA APLICAR PROMOCION',
  `PRECIO` decimal(11,2) DEFAULT NULL COMMENT 'CALCULABLE: PRECIO PRODUCTO - PORCENTAJE DSCTO',
  `MONTO_DSCTO` decimal(11,2) DEFAULT NULL COMMENT 'CALCULABLE: PORCENTAJE DSCTO DE PROMOCION EN DECIMAL * PRECIO DE PRODUCTO',
  `PORCENTAJE_DSCTO` int DEFAULT NULL,
  `FECHA_INICIO` datetime DEFAULT NULL,
  `FECHA_FIN` datetime DEFAULT NULL,
  `USUARIO_REG` varchar(80) DEFAULT NULL,
  `FECHA_REG` datetime DEFAULT NULL,
  `USUARIO_MOD` varchar(80) DEFAULT NULL,
  `FECHA_MOD` datetime DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL COMMENT 'A:ACTIVO, I:INACTIVO, X:ANULADO',
  PRIMARY KEY (`ID_PROMOCION`),
  FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO`(ID_PRODUCTO)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `CUPON` (
  `ID_CUPON` int NOT NULL,
  `DESCRIPCION` varchar(50) NOT NULL,
  `PORCENTAJE_DSCTO` int DEFAULT NULL,
  `FECHA_INICIO` datetime DEFAULT NULL,
  `FECHA_FIN` datetime DEFAULT NULL,
  `USUARIO_REG` varchar(80) DEFAULT NULL,
  `FECHA_REG` datetime DEFAULT NULL,
  `USUARIO_MOD` varchar(80) DEFAULT NULL,
  `FECHA_MOD` datetime DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL COMMENT 'A:ACTIVO, I:INACTIVO, X:ANULADO, U:USO',
  PRIMARY KEY (`ID_CUPON`,`DESCRIPCION`)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `PEDIDO` (
  `ID_PEDIDO` int NOT NULL,
  `ID_CUPON` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `NRO_PEDIDO` char(18) NOT NULL,
  `MONTO_DSCTO` decimal(11,2) DEFAULT NULL COMMENT 'CALCULABLE: PORCENTAJE DE CUPON EN DECIMAL * SUBTOTAL',
  `SUBTOTAL` decimal(11,2) DEFAULT NULL COMMENT 'CALCULABLE: SUMA DEL IMPORTE',
  `TOTAL` decimal(11,2) DEFAULT NULL COMMENT 'CALCULABLE: SUBTOTAL - MONTO DSCTO',
  `FECHA_REG` datetime DEFAULT NULL,
  `USUARIO_MOD` varchar(80) DEFAULT NULL,
  `FECHA_MOD` datetime DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL COMMENT 'A:ACTIVO, I:INACTIVO, X:ANULADO, P:DEVUELTO PARCIAL, T:DEVOLUCION TOTAL',
  PRIMARY KEY (`ID_PEDIDO`,`NRO_PEDIDO`),
  FOREIGN KEY (`ID_CUPON`) REFERENCES `CUPON`(ID_CUPON),
  FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO`(ID_USUARIO)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `PEDIDO_DETALLE` (
  `ID_PEDIDO_DETALLE` int NOT NULL,
  `ID_PEDIDO` int NOT NULL,
  `ID_PRODUCTO` int NOT NULL,
  `CANTIDAD` int DEFAULT NULL,
  `PRECIO` decimal(11,2) DEFAULT NULL,
  `IMPORTE` decimal(11,2) DEFAULT NULL COMMENT 'CALCULABLE:CANTIDAD X PRECIO',
  `IMPORTE_DSCTO` decimal(11,2) DEFAULT NULL COMMENT 'OBETENER CAMPO PRECIO DE LA TABLA PROMOCION',
  `USUARIO_REG` varchar(80) DEFAULT NULL,
  `FECHA_REG` datetime DEFAULT NULL,
  `USUARIO_MOD` varchar(80) DEFAULT NULL,
  `FECHA_MOD` datetime DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL COMMENT 'A:ACTIVO, I:INACTIVO, X:ANULADO, D: DEVUELTO',
  PRIMARY KEY (`ID_PEDIDO_DETALLE`),
  FOREIGN KEY (`ID_PEDIDO`) REFERENCES `PEDIDO`(ID_PEDIDO),
  FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO`(ID_PRODUCTO)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*
CREATE TABLE `DEVOLUCION` (
  `ID_DEVOLUCION` int NOT NULL,
  `ID_PEDIDO` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `NRO_PEDIDO` char(18) NOT NULL,
  `MONTO_DSCTO` decimal(11,2) DEFAULT NULL COMMENT 'CALCULABLE: PORCENTAJE DE CUPON EN DECIMAL * SUBTOTAL',
  `SUBTOTAL` decimal(11,2) DEFAULT NULL COMMENT 'CALCULABLE: SUMA DEL IMPORTE',
  `TOTAL` decimal(11,2) DEFAULT NULL COMMENT 'CALCULABLE: SUBTOTAL - MONTO DSCTO',
  `FECHA_REG` datetime DEFAULT NULL,
  `USUARIO_MOD` varchar(80) DEFAULT NULL,
  `FECHA_MOD` datetime DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL COMMENT 'A:ACTIVO, I:INACTIVO, X:ANULADO, P:DEVUELTO PARCIAL, T:DEVOLUCION TOTAL',
  PRIMARY KEY (`ID_DEVOLUCION`),
  FOREIGN KEY (`ID_PEDIDO`) REFERENCES `PEDIDO`(ID_PEDIDO),
  FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO`(ID_USUARIO)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `DEVOLUCION_DETALLE` (
  `ID_DEVOLUCION_DETALLE` int NOT NULL,
  `ID_DEVOLUCION` int NOT NULL,
  `ID_PRODUCTO` int NOT NULL,
  `CANTIDAD` int DEFAULT NULL,
  `PRECIO` decimal(11,2) DEFAULT NULL,
  `IMPORTE` decimal(11,2) DEFAULT NULL COMMENT 'CALCULABLE: CANTIDAD X PRECIO',
  `IMPORTE_DSCTO` decimal(11,2) DEFAULT NULL COMMENT 'OBETENER CAMPO PRECIO DE LA TABLA PROMOCION',
  `USUARIO_REG` varchar(80) DEFAULT NULL,
  `FECHA_REG` datetime DEFAULT NULL,
  `USUARIO_MOD` varchar(80) DEFAULT NULL,
  `FECHA_MOD` datetime DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL COMMENT 'A: DEVOLUCION ACEPTADA, C:DEVOLUCION CANCELADA',
  PRIMARY KEY (`ID_DEVOLUCION_DETALLE`),
  FOREIGN KEY (`ID_DEVOLUCION`) REFERENCES `DEVOLUCION`(ID_DEVOLUCION),
  FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO`(ID_PRODUCTO)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `TRANSACCION` (
  `ID_TRANSACCION` int NOT NULL,
  `ID_PEDIDO` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `MONTO` decimal(11,2) DEFAULT NULL,
  `TIPO_MONEDA` varchar(20) DEFAULT NULL,
  `FECHA_REG` datetime DEFAULT NULL,
  `USUARIO_MOD` varchar(80) DEFAULT NULL,
  `FECHA_MOD` datetime DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL COMMENT 'C:COMPLETO, I:INCOMPLETO, X:ANULADO',
  PRIMARY KEY (`ID_TRANSACCION`),
  FOREIGN KEY (`ID_PEDIDO`) REFERENCES `PEDIDO`(ID_PEDIDO),
  FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO`(ID_USUARIO)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


*/




